version: 2.1
orbs:
  node: circleci/node@5
  aws-cli: circleci/aws-cli@4.0
  aws-s3: circleci/aws-s3@4.0

jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Run Build Static
          command: cd www && yarn build:static
          environment:
            DATADOG_APPLICATION_ID: 67b751ad-00be-4e09-87d7-fb4a7df1e134
            DATADOG_CLIENT_TOKEN: pub8348e62acc94288326c75164f1833c28
            DATADOG_SERVICE: marketing-website
            DATADOG_SITE: datadoghq.com
            STATIC_BUILD: true
      - run:
          name: Run tests
          command: yarn test --passWithNoTests
      - persist_to_workspace:
          root: ~/project/www
          paths:
            - out

  deploy:
    docker:
      - image: cimg/base:stable
    environment:
      AWS_DEFAULT_REGION: us-east-2
    steps:
      - checkout
      - attach_workspace:
          at: ~/project/www
      - aws-cli/setup:
          role_arn: arn:aws:iam::905418149376:role/CircleCI
      - aws-s3/sync:
          arguments: |
            --delete
          from: /home/circleci/project/www/out
          to: s3://marketing-website-assets-905418149376
      - run:
          name: Deploy to CloudFront
          command: aws cloudfront create-invalidation --distribution-id E2KP9J5JTG1DGX --paths "/*"
          environment:
            # CloudFront's CreateInvalidation API occasionally has a high error
            # rate, so we increase the number of attempted retries to
            # compensate.
            AWS_MAX_ATTEMPTS: 10

workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main
