version: 2.1
orbs:
  node: circleci/node@5
  aws-cli: circleci/aws-cli@4.0
  aws-s3: circleci/aws-s3@4.0

executors:
  my-executor:
    docker:
      - image: cimg/base:stable
    working_directory: /www

jobs:
  build:
    executor: my-executor
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Run Build Static
          command: cd www && yarn build:static
          environment:
            STATIC_BUILD: true
      - run:
          name: Run tests
          command: yarn test --passWithNoTests
      - persist_to_workspace:
          root: out
          paths:
            - *

  deploy:
    executor: my-executor
    steps:
      - attach_workspace:
          at: /www/out
      - checkout
      - aws-cli/setup:
          role_arn: ${ROLE_ARN}
      - aws-s3/sync:
          arguments: |
            --acl public-read
          from: /www/out/*
          to: ${BUCKET_NAME}

workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
