version: 2.1
orbs:
  node: circleci/node@5
  aws-cli: circleci/aws-cli@4.0
  aws-s3: circleci/aws-s3@4.0

jobs:
  deploy-cms:
    docker:
      - image: cimg/node:21.1.0 # update this on add staging branch
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Deploy Sanity CMS
          command: SANITY_AUTH_TOKEN="${SANITY_AUTH_TOKEN}" yarn deploy
          working_directory: ~/project/sanity

  build:
    executor: node/default
    parameters:
      env:
        type: enum
        description: controls the environment to build for
        enum: ['staging', 'production']
      is_indexing_allowed:
        type: boolean
        description: Controls whether site crawling is enabled. When set to false a no-index tag is added to the site.
        default: false
      is_local_cms_data_enabled:
        type: boolean
        description: Controls whether the site is loaded using checked in config/ local data.
        default: true
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Run Build Static
          command: cd www && NEXT_PUBLIC_IS_INDEXING_ALLOWED=<< parameters.is_indexing_allowed >> NEXT_PUBLIC_IS_LOCAL_CMS_DATA_ENABLED=<< parameters.is_local_cms_data_enabled >> yarn build:static
          environment:
            DATADOG_APPLICATION_ID: 67b751ad-00be-4e09-87d7-fb4a7df1e134
            DATADOG_CLIENT_TOKEN: pub8348e62acc94288326c75164f1833c28
            DATADOG_SERVICE: marketing-website
            DATADOG_SITE: datadoghq.com
            NEXT_PUBLIC_ENV: << parameters.env >>
      - run:
          name: Run tests
          command: yarn test --passWithNoTests
      - persist_to_workspace:
          root: ~/project/www
          paths:
            - out

  deploy:
    docker:
      - image: cimg/base:stable
    environment:
      AWS_DEFAULT_REGION: us-east-2
    parameters:
      s3-uri:
        type: enum
        enum: [
            's3://marketing-website-assets-905418149376-stg', # staging
            's3://marketing-website-assets-905418149376', # production
          ]
      cloudfront-distribution-id:
        type: enum
        enum: [
            'E1DEC4PZRVMULZ', # staging
            'E2KP9J5JTG1DGX', # production
          ]
    steps:
      - checkout
      - attach_workspace:
          at: ~/project/www
      - aws-cli/setup:
          role_arn: arn:aws:iam::905418149376:role/CircleCI
      - aws-s3/sync:
          arguments: |
            --delete
          from: /home/circleci/project/www/out
          to: << parameters.s3-uri >>
      - run:
          name: Deploy to CloudFront
          command: aws cloudfront create-invalidation --distribution-id << parameters.cloudfront-distribution-id >> --paths "/*"
          environment:
            # CloudFront's CreateInvalidation API occasionally has a high error
            # rate, so we increase the number of attempted retries to
            # compensate.
            AWS_MAX_ATTEMPTS: 10

workflows:
  build-and-deploy:
    jobs:
      - deploy-cms:
          name: deploy-cms-schema-update
          filters:
            branches:
              only: main
      - build:
          name: build-staging
          requires:
            - deploy-cms-schema-update
          filters:
            branches:
              only: main
          env: staging
          is_indexing_allowed: false
          is_local_cms_data_enabled: false
      - build:
          name: build-production
          filters:
            branches:
              only: test-build-deploy
          env: production
          is_indexing_allowed: true
          is_local_cms_data_enabled: true
      - deploy:
          name: deploy-staging
          requires:
            - build-staging
          filters:
            branches:
              only: main
          s3-uri: s3://marketing-website-assets-905418149376-stg
          cloudfront-distribution-id: E1DEC4PZRVMULZ
      - deploy:
          name: deploy-production
          requires:
            - build-production
          filters:
            branches:
              only: test-build-deploy # TODO: update this to "test-build-deploy" branch to test
          s3-uri: s3://marketing-website-assets-905418149376-stg #staging environment
          cloudfront-distribution-id: E1DEC4PZRVMULZ #staging environment
