name: Check PR & Deploy
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  deploy-cms:
    name: Deploy CMS
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy-sanity.yml
    secrets:
      sanity-auth-token: ${{ secrets.SANITY_DEPLOY_TOKEN }}
    with:
      directory: 'sanity'
