name: Check PR & Deploy
on:
  pull_request:
  push:
    branches:
      - main
      - production

jobs:
  benchmark-web:
    name: Test & Benchmark
    uses: ./.github/workflows/benchmark.yml
    with:
      directory: 'www'

  deploy-web:
    name: Deploy Vercel
    needs: [benchmark-web]
    uses: ./.github/workflows/deploy-vercel.yml
    secrets:
      vercel-token: ${{ secrets.VERCEL_TOKEN }}
      github-token: ${{ secrets.GITHUB_TOKEN }}
    with:
      vercel-project-id: ${{ vars.VERCEL_PROJECT_ID }}
      vercel-storybook-project-id: ${{ vars.VERCEL_STORYBOOK_PROJECT_ID }}
      vercel-org-id: ${{ vars.VERCEL_ORG_ID }}
      directory: 'www'

  # deploy-cms:
  #   name: Deploy CMS
  #   if: github.ref == 'refs/heads/production'
  #   needs: [benchmark-web]
  #   uses: ./.github/workflows/deploy-sanity.yml
  #   secrets:
  #     sanity-auth-token: ${{ secrets.SANITY_DEPLOY_TOKEN }}
  #   with:
  #     directory: 'sanity'
