name: Check PR & Deploy
on:
  pull_request:
  push:
    branches:
      - main
      - production

jobs:
  benchmark-web:
    name: Test & Benchmark
    uses: ./.github/workflows/benchmark.yml
    with:
      directory: 'www'

  # TODO: This is not actually helpful until we can omit draft documents from validation.
  # test-sanity:
  #   name: Test Sanity
  #   uses: ./.github/workflows/test-sanity.yml
  #   with:
  #     directory: 'sanity'

  # removed test-sanity from 'needs'
  deploy-cms:
    name: Deploy CMS
    if: github.ref == 'refs/heads/production'
    needs: [benchmark-web]
    uses: ./.github/workflows/deploy-sanity.yml
    secrets:
      sanity-auth-token: ${{ secrets.SANITY_DEPLOY_TOKEN }}
    with:
      directory: 'sanity'
