name: Deploy Sanity
on:
  workflow_call:
    secrets:
      sanity-auth-token:
        required: true
    inputs:
      directory:
        required: true
        type: string

jobs:
  # Make sure updates to the CMS are deployed when prod is updated
  deploy-cms:
    name: Deploy Sanity CMS
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.directory }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/yarn-setup
      - run: SANITY_AUTH_TOKEN="${{ secrets.sanity-auth-token }}" yarn deploy
