name: Deploy
on:
  workflow_call:
    secrets:
      vercel-token:
        required: true
      github-token:
        required: true
    inputs:
      directory:
        required: true
        type: string
      vercel-project-id:
        required: true
        type: string
      vercel-org-id:
        required: true
        type: string



jobs:
  # Create a preview deployment on PR pushes (not main or prod)
  deploy-preview:
    name: Preview
    if: github.ref != 'refs/head/main'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.directory }}
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/vercel-action@v20
        with:
          vercel-project-id: ${{ inputs.vercel-project-id }}
          vercel-org-id: ${{ inputs.vercel-org-id }}
          scope: ${{ inputs.vercel-org-id }}
          vercel-token: ${{ secrets.vercel-token }}
          github-token: ${{ secrets.github-token }}

  # Create an aliased deployment on pushes to main
  deploy-prod:
    name: Production
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.directory }}
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/vercel-action@v20
        with:
          vercel-args: '--prod'
          vercel-project-id: ${{ inputs.vercel-project-id }}
          vercel-org-id: ${{ inputs.vercel-org-id }}
          scope: ${{ inputs.vercel-org-id }}
          vercel-token: ${{ secrets.vercel-token }}
          github-token: ${{ secrets.github-token }}
