name: Deploy
on:
  push:
    branches:
      - cms-updates

permissions:
  contents: write
  pull-requests: write

jobs:
  deploy-preview-with-static-cms:
    name: Preview
    runs-on: ubuntu-latest
    outputs:
      preview-url: ${{ steps.vercel.outputs.preview-url }}
    defaults:
      run:
        working-directory: ${{ inputs.directory }}
    steps:
      - uses: ./.github/workflows/yarn-setup
      - name: set env to static build
        run: yarn STATIC_BUILD=true
      - uses: actions/checkout@v3
      - uses: amondnet/vercel-action@v25
        id: vercel
        with:
          vercel-project-id: ${{ inputs.vercel-project-id }}
          vercel-org-id: ${{ inputs.vercel-org-id }}
          scope: ${{ inputs.vercel-org-id }}
          vercel-token: ${{ secrets.vercel-token }}
          github-token: ${{ secrets.github-token }}